<a href="https://colab.research.google.com/github/Amanpatni211/Echelon-Form/blob/main/echelon_form.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
'''
 This notebook is playground for making some matrix concepts of solving system of linear equations.
I want to work on this till my test and even later if I wish
so theoritically I know what should be done to do any method, the crux is to first write a algorithm and then is to code it in python
I will start with echelon form then proceed further in coordial manner.
So what is Echelon form ; lets look into notes for that.
so it is a generalization of upper triangular matrix ; it is not unique 
'''
#problem statement : Convert any given matrix into one of its echelon form.
#now we will ask for a input for any mxn matrix
#so I will take the input row wise
m =  int(input("Enter the number of rows"))
n = int(input("Enter the numberof columns"))
imx= np.zeros((m,n))
for i in range(1,m+1):
  for j in range(1,n+1):
    a = float(input("Enter the" + str(i)+","+str(j)+"term"))
    imx[i-1][j-1] = a
print(imx)


In [ ]:
imx =[[32,322,33],[0,65,77],[5,6,7]]
m=3
n=3

In [ ]:
imx[2][2]

7

In [ ]:
#now I have the matrix with me, next I am going to write the algorithm
#step 1 is if there is any 0 row matrix then swap it in the bottom
#lets execute that.
#logic to do this is
'''
step 1: identify the zero rows
step 2 : make two matrices; one with zero rows and the other with non zero rows
step 3 : concat them , such that the zero row matrix will get the last terms
'''
nm_non_zero =[]
nm_zero =[]
for i in range(1,m+1):
  test_m = []
  for j in range(1,n+1):
    if imx[i-1][j-1] ==0 :
      test_m.append(0)
    else:
      test_m.append(1)
  print(test_m)
  if test_m == list(np.zeros(n)):
    nm_zero.append(imx[i-1])
  else:
    nm_non_zero.append(imx[i-1])
#now we will concatenate the two matrices
print(nm_non_zero)
print(nm_zero)
nm_non_zero = np.array(nm_non_zero)
nm_zero = np.array(nm_zero)
if len(nm_zero)!=0 :

  nm = np.concatenate((nm_non_zero,nm_zero),axis = 0)
else:
  nm = nm_non_zero

print(nm)
      



[1, 1, 1]
[0, 1, 1]
[1, 1, 1]
[[32, 322, 33], [0, 65, 77], [5, 6, 7]]
[]
[[ 32 322  33]
 [  0  65  77]
 [  5   6   7]]


In [ ]:
print(nm)

[[ 32 322  33]
 [  0  65  77]
 [  5   6   7]]


In [ ]:
#now lets get into step 2 which is converting it in upper triangle system
#so I have to make sure that leading term of any row is on the right side of leading term of the preceeding row
#this seems to be hard for me..anyway first I will make my column 1 with only the top entry being non-zero;then
#i will make the same in other rows too..so let us find the steps to do the same..
#firstly I will code down all the row operations for any matrix

#so basically I have to make 3 functions; ROW_OPERATION = ro
#ro1 is for swapping two rows

def ro1(m, i,j):
  m[[i,j]] = m[[j,i]]
  return m

#row operation 2 is ro2 is to multiply any given row with a scalar
def ro2(m,j,alpha):
  m[j] = list(alpha*np.array(m[j]))
  return m

#row operation 3 is ro3 is to replace a row with row := row + alpha*any_other_row
def ro3(m,i,j,alpha):
  m[i]=list( np.array(m[i]) + alpha*np.array(m[j]))
  return m







In [ ]:
#@title Default title text
#before taking the final step, i will have to first make sure that all leading terms are arranged according to the hierarchy of leading term precedence
#steps are check  lets think so i can make identify the first non-zero term in every row and then sort their index and then make the new matrix with that order
#in place...lets think little further after i make this new matrix and then I will make a for loop in ehich i will see yeah so it may be possible to do further

# here i will be finding the leading terms of all matrix
'''
def leading_term_index(my ,i ):
  m = my.shape[1]
  p=0
  v=2
  while p in range(0,m) or v ==1 :
    
    if my[i][p] != 0 :
      index = p
      v=v-1
    else:
      p= p+1
  return index
'''
    

In [ ]:
#@title Default title text
m =  int(input("Enter the number of rows"))
n = int(input("Enter the numberof columns"))
im1= np.zeros((m,n))
for i in range(1,m+1):
  for j in range(1,n+1):
    a = float(input("Enter the" + str(i)+","+str(j)+"term"))
    im1[i-1][j-1] = a
print(im1)

In [ ]:
def leading_term_index_list(my):
  m = my.shape[1]
  t = my.shape[0]
  
  i=0
  leading_list = {}
  for i in range(0,t):
    p=0
    v=2
    index = -1
    for p in range(0,m):
      if v!= 1: 
        if my[i][p] != 0 :
          index = p
          v=v-1    
      p= p+1
      if index!=-1:
        leading_list[i]= p
        break 
      if p==m-1 and index==-1 :
        leading_list[i]=m+1
    aman=leading_list
    aman=sorted(aman.items(), key=lambda x: x[1], reverse=False)
  return aman

In [ ]:
type(nm_non_zero)

numpy.ndarray

In [ ]:
leading_term_index_list(nm_non_zero)


[(0, 1), (2, 1), (1, 2)]

In [ ]:
aman

[(0, 1), (2, 1), (1, 2)]

In [ ]:
#now we will make a new matrix for this all things
het_ma = []
for i in range(nm_non_zero.shape[0]):
  het_ma.append(list(nm_non_zero[aman[i][0]]))
print(het_ma)

[[32, 322, 33], [5, 6, 7], [0, 65, 77]]


In [ ]:
#so now I have to use elementary row operation to make all entries 0 below any leading entry.
#but there are some cases in which there will be we will have to make this column solved and then again we will have to make it a fucntion,but first I will sort this out
print(het_ma[1][0])

5


In [ ]:

'''
wait what do I have to do 
see once i have the list of the leading terms i should know which row has which leading term then i need to find so i have to sort it dictionary strikes as 
of now but lets write the plan
now so let us try it out should i should i not
actually what he said proves that he is very good at observations like he said Vocabulary preceeds nuances , that indeed took time to understand but
statements like this are like open source things which have the potential to transform the situation so i like it a lot and that is why i am in 
see now i can know the leading terms of all the matrix and then i will make a dictionary out of it and then i will define a new list 
i think we should code a little 
for i in range(len(het_ma)):
  chance in the
'''
def pivot_maker(m,i,j):#m is the matrix, i , j are position of the leading element
  for t in range(i+1,len(m)+1):
    
    if m[t][j]!=0 :
      alpha = ((-1)*m[i][j])/m[t][j]
      
      m[t]=ro3(m,t,j,alpha)
      m = m - m[len(m)-1]
      a = len(m)
      b= a
    
    return m




In [ ]:
print(het_ma)

[[32, 322, 33], [5, 6, 7], [0, 65, 77]]


In [ ]:
pivot_maker(het_ma,0,0)

In [ ]:
#@title Default title text
#now I will make row operations to make this entries 0
#which is really hard to code ahhh darn it
#so now lets do it.
'''
for i in range(0,n+1):

  for j in range(1+i,m+1):
    alphaa = ((-1)*nm[i][i+1])/nm[i][j]
    ro3(nm,j,0,alphaa)
  '''


so firstly write what is a echelon form?

it is updated version of a matrix which has some properties:

 1)Any row consisting of all zeros are the bottom most rows.

 2)The leading terms of all the rows is 1

 3)For any two consecutive rows, the leading term 1 of the above row is on left than the other

 4)Now RREF is reduced row echelon form is when the any column having a leading term should have only one non-zero entry.
 

In [ ]:
#how much have I progressed?
#I am making a function which will make all the leading entries as one.
def leadingTerm_one_maker(matrix):
  print(type(matrix))
  rows=len(matrix)
  columns = len(matrix[0])
  print(rows,columns)
  for i in range(rows):
    for j in range(columns):
      if matrix[i][j]!=0:
        alpha=(-1)/matrix[i][j]
        ro2(matrix,i,alpha)
        matrix[i][j]=1
        break
      else:
        j=j+1
  return matrix

In [ ]:
type(het_ma[0][0])

int

In [ ]:
leadingTerm_one_maker(het_ma)

<class 'list'>
3 3


TypeError: ignored

In [ ]:
print(het_ma)

[[1, -10.0625, -1.03125], [1, -1.2, -1.4000000000000001], [0.0, 1, -1.1846153846153846]]


In [ ]:
aman[0][1]

1

In [ ]:
#now we will make a function which will check every successive row and if there is any row which has leading 
#term in same column we will make it 0
def successive_row_0maker(matrix):
  rows=len(matrix)
  columns = len(matrix[0])
  
  for i in range(1):
    if aman[i][1]==aman[i+1][1]:
      ro3(matrix,i+1,i,-1)
    else:
      i=i+1
  return matrix



In [ ]:
successive_row_0maker(het_ma)

[[1, -10.0625, -1.03125],
 [-3.0, 39.05, 2.7249999999999996],
 [0.0, 1, -1.1846153846153846]]

In [ ]:
18.925+1.2


20.125

In [ ]:
20.125/2

10.0625